# Generated by Django 3.1.1 on 2020-09-23 00:52

import dashboard.models.methods
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200923_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Created At Help', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At Help', verbose_name='Updated At')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
            bases=(models.Model, dashboard.models.methods.Message),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard.topic', verbose_name='Parent Node')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
            bases=(models.Model, dashboard.models.methods.Topic),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Created At Help', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At Help', verbose_name='Updated At')),
                ('read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.message', verbose_name='Message')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['read', '-created_at', 'user'],
            },
            bases=(models.Model, dashboard.models.methods.Notice),
        ),
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dashboard.topic', verbose_name='Topic'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('tree_id', 'level', 'code'), name='unique_code'),
        ),
        migrations.AddConstraint(
            model_name='notice',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_recipient'),
        ),
    ]
